import time
from collections.abc import Callable

from .book_side import BookSide
from .state_validation import validate_state
from .order_validation import validate_cancel_request, validate_modify_request, validate_new_order
from .price_level import OrderNode, PriceLevel
from .types.enums import EventType, OrderStatus, OrderType, Side, TimeInForce
from .types.events import Event
from .types.instruments import Instrument
from .types.orders import Order
from .types.requests import CancelOrderRequest, ModifyOrderRequest, NewOrderRequest


class OrderBook:
    """
    Manages the book state incl. order submission, matching, cancellation, and modification

    Attributes:
    - instrument: financial instrument traded by the order book
    - bids: buy side of the order book
    - asks: sell side of the order book
    - order_index: resting orders indexed by order ID
    - events: events generated by the matching engine
    """
    def __init__(
        self,
        instrument: Instrument,
        clock: Callable[[], int] | None = None
    ) -> None:
        if not isinstance(instrument, Instrument):
            raise ValueError("Instrument must be an Instrument")

        self.instrument = instrument
        self.clock = clock

        self.bids = BookSide(Side.BUY)
        self.asks = BookSide(Side.SELL)

        self.order_index: dict[int, OrderNode] = {}
        self.events: list[Event] = []

        self.next_order_id = 1
        self.next_trade_id = 1
        self.event_sequence = 1

    def submit_order(self, request: NewOrderRequest) -> Order:
        """
        Validates, accepts, matches, and potentially rests a new order
        """
        try:
            validate_new_order(request, self.instrument)
        except ValueError as error:
            self.emit_event(
                EventType.ORDER_REJECTED,
                {
                    "request_id": request.request_id,
                    "client_id": request.client_id,
                    "reason": str(error)
                }
            )
            raise

        order = self.create_order(request)

        self.emit_event(
            EventType.ORDER_ACCEPTED,
            self.get_order_details(order)
        )

        # Cancel the order if FOK and cannot be fully filled
        if order.time_in_force is TimeInForce.FOK and not self.can_fully_fill(order):
            cancelled_size = order.size
            order.size = 0
            order.status = OrderStatus.CANCELLED

            self.emit_event(
                EventType.ORDER_CANCELLED,
                {
                    **self.get_order_details(order),
                    "cancelled_size": cancelled_size,
                    "reason": "Insufficient liquidity for FOK order"
                }
            )

            return order

        # Otherwise, match the order
        self.match_order(order)

        if order.size == 0:
            order.status = OrderStatus.FILLED

            self.emit_event(
                EventType.ORDER_FILLED,
                self.get_order_details(order)
            )

            return order

        # Rest the order if LIMIT and cannot be fully filled
        if order.order_type is OrderType.LIMIT and order.time_in_force is TimeInForce.GTC:
            order.status = OrderStatus.ACTIVE
            self.insert_resting_order(order)

            self.emit_event(
                EventType.ORDER_RESTED,
                self.get_order_details(order)
            )

            return order

        if order.time_in_force is TimeInForce.FOK:
            raise RuntimeError(
                "FOK order remained unfilled after liquidity check"
            )

        cancelled_size = order.size
        order.size = 0
        order.status = OrderStatus.CANCELLED

        # Cancel order if IOC and remainder > 0
        self.emit_event(
            EventType.ORDER_REMAINDER_CANCELLED,
            {
                **self.get_order_details(order),
                "cancelled_size": cancelled_size,
                "reason": "Unfilled IOC remainder cancelled"
            }
        )

        return order

    def cancel_order(self, request: CancelOrderRequest) -> Event:
        """
        Cancels an active resting order
        """
        try:
            validate_cancel_request(request, self.order_index)
        except ValueError as error:
            self.emit_event(
                EventType.CANCEL_REJECTED,
                {
                    "request_id": request.request_id,
                    "order_id": request.order_id,
                    "client_id": request.client_id,
                    "reason": str(error)
                }
            )
            raise

        order_node = self.order_index[request.order_id]
        order = order_node.order
        cancelled_size = order.size

        self.remove_resting_order(order_node)

        order.size = 0
        order.status = OrderStatus.CANCELLED

        return self.emit_event(
            EventType.ORDER_CANCELLED,
            {
                **self.get_order_details(order),
                "request_id": request.request_id,
                "cancelled_size": cancelled_size
            }
        )
    
    def modify_order(self, request: ModifyOrderRequest) -> Event:
        """
        Modifies the price and/or size of an active resting order
        """
        try:
            validate_modify_request(request, self.instrument, self.order_index)
        except ValueError as error:
            self.emit_event(
                EventType.MODIFY_REJECTED,
                {
                    "request_id": request.request_id,
                    "order_id": request.order_id,
                    "client_id": request.client_id,
                    "reason": str(error)
                }
            )
            raise

        order_node = self.order_index[request.order_id]
        order = order_node.order

        old_price = order.price
        old_size = order.size

        target_price = old_price if request.new_price is None else request.new_price
        target_size = old_size if request.new_size is None else request.new_size

        if target_price is None:
            raise RuntimeError("Resting order has no price")

        price_changed = target_price != old_price
        size_increased = target_size > old_size

        # If the order price has changed, re-insert into the book
        if price_changed:
            self.remove_resting_order(order_node)

            order.price = target_price
            order.size = target_size

            self.match_order(order)

            if order.size > 0:
                order.status = OrderStatus.ACTIVE
                self.insert_resting_order(order)
            else:
                order.status = OrderStatus.FILLED

        # If the order size has increased, re-insert into the book
        elif size_increased:
            book_side = (
                self.bids
                if order.side is Side.BUY
                else self.asks
            )

            book_side.remove_order_node(order_node)

            order.size = target_size
            order.status = OrderStatus.ACTIVE

            book_side.add_order_node(order_node)

        # Size decrease does not affect FIFO priority
        else:
            if order_node.tree_node is None:
                raise RuntimeError("Resting order has no price level")

            price_level = order_node.tree_node.price_level
            price_level.update_node_size(order_node, target_size)

            order.status = OrderStatus.ACTIVE

        return self.emit_event(
            EventType.ORDER_MODIFIED,
            {
                **self.get_order_details(order),
                "request_id": request.request_id,
                "old_price": old_price,
                "new_price": target_price,
                "old_size": old_size,
                "new_size": target_size
            }
        )

    def match_order(self, order: Order) -> None:
        """
        Matches an incoming order against resting orders using price-time priority
        """
        if order.side is Side.BUY:
            maker_book = self.asks
        else:
            maker_book = self.bids

        while order.size > 0:
            maker_level = maker_book.get_best_level()

            if maker_level is None:
                break

            maker_price = maker_level.price

            if order.order_type is OrderType.LIMIT:
                if order.price is None:
                    raise RuntimeError("Limit order has no price")

                # Bid is too low
                if order.side is Side.BUY and order.price < maker_price:
                    break

                # Ask is too high
                if order.side is Side.SELL and order.price > maker_price:
                    break

            # Match against oldest order in queue
            maker_node = maker_level.get_first()

            if maker_node is None:
                raise RuntimeError("Best price level is empty")

            maker_order = maker_node.order
            trade_size = min(order.size, maker_order.size)

            order.size -= trade_size
            maker_remaining_size = maker_order.size - trade_size

            # Remove the resting order if filled
            if maker_remaining_size == 0:
                self.remove_resting_order(maker_node)

                maker_order.size = 0
                maker_order.status = OrderStatus.FILLED
            
            # Otherwise, update the node size
            else:
                maker_level.update_node_size(
                    maker_node,
                    maker_remaining_size
                )

                maker_order.status = OrderStatus.ACTIVE

            self.emit_event(
                EventType.TRADE_EXECUTED,
                {
                    "trade_id": self.generate_trade_id(),
                    "maker_order_id": maker_order.order_id,
                    "maker_client_id": maker_order.client_id,
                    "taker_order_id": order.order_id,
                    "taker_client_id": order.client_id,
                    "taker_side": order.side.value,
                    "trade_price": maker_price,
                    "trade_size": trade_size
                }
            )

            maker_event_type = (
                EventType.ORDER_FILLED
                if maker_order.size == 0
                else EventType.ORDER_PARTIALLY_FILLED
            )

            self.emit_event(
                maker_event_type,
                self.get_order_details(maker_order)
            )

    def can_fully_fill(self, order: Order) -> bool:
        """
        Checks whether an order can be completely filled immediately
        """
        if order.side is Side.BUY:
            opposite_side = self.asks
        else:
            opposite_side = self.bids

        # Order size for immediate execution
        remaining_size = order.size

        # Iterate through ordered price levels
        for price_level in opposite_side.get_price_levels_in_order():
            level_price = price_level.price

            if order.order_type is OrderType.LIMIT:
                if order.price is None:
                    raise RuntimeError("Limit order has no price")

                # Bid is too low
                if order.side is Side.BUY and level_price > order.price:
                    break

                # Ask is too high
                if order.side is Side.SELL and level_price < order.price:
                    break

            remaining_size -= price_level.total_size

            if remaining_size <= 0:
                return True

        return False

    def create_order(self, request: NewOrderRequest) -> Order:
        """
        Creates an accepted order from a new order request
        """
        return Order(
            order_id=self.generate_order_id(),
            request_id=request.request_id,
            client_id=request.client_id,
            side=request.side,
            order_type=request.order_type,
            time_in_force=request.time_in_force,
            size=request.size,
            timestamp=self.generate_timestamp(),
            price=request.price,
            status=OrderStatus.ACTIVE
        )

    def insert_resting_order(self, order: Order) -> None:
        """
        Adds an order to the appropriate side of the book
        """
        order_node = OrderNode(order)

        if order.side is Side.BUY:
            self.bids.add_order_node(order_node)
        else:
            self.asks.add_order_node(order_node)

        # Update the order index
        self.order_index[order.order_id] = order_node

    def remove_resting_order(self, order_node: OrderNode) -> None:
        """
        Removes an order from the book and order index
        """
        if order_node.order.side is Side.BUY:
            self.bids.remove_order_node(order_node)
        else:
            self.asks.remove_order_node(order_node)

        # Update the order index
        del self.order_index[order_node.order.order_id]

    def emit_event(
            self,
            event_type: EventType,
            details: dict[str, object]
        ) -> Event:
            """
            Creates and stores an engine event
            """
            event_details = {
                "symbol": self.instrument.symbol,
                **details
            }

            event = Event(
                sequence=self.generate_event_sequence(),
                timestamp=self.generate_timestamp(),
                event_type=event_type,
                details=event_details
            )

            self.events.append(event)
            return event
    
    def get_order_details(self, order: Order) -> dict[str, object]:
        """
        Returns common order fields used in engine events
        """
        return {
            "request_id": order.request_id,
            "order_id": order.order_id,
            "client_id": order.client_id,
            "side": order.side.value,
            "order_type": order.order_type.value,
            "time_in_force": order.time_in_force.value,
            "price": order.price,
            "original_size": order.original_size,
            "remaining_size": order.size,
            "status": order.status.value
        }

    def generate_order_id(self) -> int:
        order_id = self.next_order_id
        self.next_order_id += 1
        return order_id

    def generate_trade_id(self) -> int:
        trade_id = self.next_trade_id
        self.next_trade_id += 1
        return trade_id

    def generate_event_sequence(self) -> int:
        sequence = self.event_sequence
        self.event_sequence += 1
        return sequence

    def generate_timestamp(self) -> int:
        if self.clock is not None:
            return self.clock()

        return time.time_ns()

    # QUERY FUNCTIONS
    def get_bid_side(self) -> BookSide:
        return self.bids

    def get_ask_side(self) -> BookSide:
        return self.asks

    def get_order(self, order_id: int) -> Order | None:
        order_node = self.order_index.get(order_id)
        return None if order_node is None else order_node.order

    def get_order_node(self, order_id: int) -> OrderNode | None:
        return self.order_index.get(order_id)

    def has_order(self, order_id: int) -> bool:
        return order_id in self.order_index

    def get_best_bid(self) -> PriceLevel | None:
        return self.bids.get_best_level()

    def get_best_ask(self) -> PriceLevel | None:
        return self.asks.get_best_level()

    def get_best_bid_price(self) -> int | None:
        return self.bids.get_best_price()

    def get_best_ask_price(self) -> int | None:
        return self.asks.get_best_price()

    def get_bid_ask_spread(self) -> int | None:
        best_bid = self.get_best_bid_price()
        best_ask = self.get_best_ask_price()

        if best_bid is None or best_ask is None:
            return None

        return best_ask - best_bid

    def get_mid_price(self) -> float | None:
        best_bid = self.get_best_bid_price()
        best_ask = self.get_best_ask_price()

        if best_bid is None or best_ask is None:
            return None

        return (best_bid + best_ask) / 2

    def get_depth_at_price(self, side: Side, price: int) -> int:
        book_side = self.bids if side is Side.BUY else self.asks
        tree_node = book_side.get_price_level(price)
        return 0 if tree_node is None else tree_node.price_level.total_size

    def get_orders_at_price(self, side: Side, price: int) -> list[Order]:
        book_side = self.bids if side is Side.BUY else self.asks
        tree_node = book_side.get_price_level(price)

        orders: list[Order] = []

        if tree_node is None:
            return orders

        current = tree_node.price_level.head

        while current is not None:
            orders.append(current.order)
            current = current.next

        return orders

    # SNAPSHOT FUNCTIONS
    def get_side_snapshot(self, side: Side) -> list[dict[str, object]]:
        book_side = self.bids if side is Side.BUY else self.asks

        snapshot: list[dict[str, object]] = []

        for price_level in book_side.get_price_levels_in_order():
            snapshot.append(
                {
                    "side": side.value,
                    "price": price_level.price,
                    "total_size": price_level.total_size,
                    "order_count": price_level.order_count
                }
            )

        return snapshot

    def get_book_snapshot(self) -> dict[str, object]:
        best_bid = self.get_best_bid()
        best_ask = self.get_best_ask()

        return {
            "timestamp_ns": self.generate_timestamp(),
            "symbol": self.instrument.symbol,
            "best_bid_price": self.get_best_bid_price(),
            "best_bid_size": None if best_bid is None else best_bid.total_size,
            "best_ask_price": self.get_best_ask_price(),
            "best_ask_size": None if best_ask is None else best_ask.total_size,
            "spread": self.get_bid_ask_spread(),
            "mid_price": self.get_mid_price(),
            "active_order_count": len(self.order_index),
            "bids": self.get_side_snapshot(Side.BUY),
            "asks": self.get_side_snapshot(Side.SELL)
        }

    def is_empty(self) -> bool:
        return self.bids.is_empty() and self.asks.is_empty()

    def reset(self) -> None:
        self.bids = BookSide(Side.BUY)
        self.asks = BookSide(Side.SELL)

        self.order_index.clear()
        self.events.clear()

        self.next_order_id = 1
        self.next_trade_id = 1
        self.event_sequence = 1

    def validate_state(self) -> None:
        validate_state(self)